main: ru.cororo.mcipsauth.McIpsAuth
name: AuthMeIpsBridge
version: ${version}
description: Minecraft IPS auth with AuthMe
author: Cororo
depend: [ AuthMe ]
commands:
  fixips:
    description: Register the player on the forum again on their next login
permissions:
  mcipsauth.admin:
    description: Allows /fixips
    default: op
